"""Render the data dictionary of the published tables from the dbt project's YAML.

Usage:
  uv run python -m data.dictionary            # rewrite data/DICTIONARY.md (make data-docs)
  uv run python -m data.dictionary --check    # fail if it's out of date (the test suite runs this)

Table and column descriptions are written once, in the YAML next to each published dbt model. This
module renders them for people (DICTIONARY.md and each release's notes); `data.release` also embeds
them in the Parquet files and the DuckDB catalog.
"""

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from sco import graph

TRANSFORM_DIR = graph.ROOT / "data" / "transform"
DICTIONARY = graph.ROOT / "data" / "DICTIONARY.md"

# {table: {"description": str, "columns": {column: {"type": str, "description": str}}}}
Tables = dict[str, dict]


def published_tables(manifest: Path) -> Tables:
    """Published models (tag:published) from a dbt manifest, data before meta_* tables, each in name
    order, columns in YAML order."""
    nodes = json.loads(manifest.read_text())["nodes"].values()
    tables, missing = {}, []
    for node in sorted(nodes, key=lambda n: (n["alias"].startswith("meta_"), n["alias"])):
        if node["resource_type"] != "model" or "published" not in node["tags"]:
            continue
        name = node["alias"]
        if not node["description"]:
            missing.append(name)
        columns = {}
        for column in node["columns"].values():
            if not (column["description"] and column["data_type"]):
                missing.append(f"{name}.{column['name']}")
            columns[column["name"]] = {
                "type": column["data_type"],
                "description": " ".join(column["description"].split()),
            }
        tables[name] = {"description": " ".join(node["description"].split()), "columns": columns}
    if missing:
        raise SystemExit(
            "error: published tables and columns need a description and data_type in their YAML: "
            + ", ".join(missing)
        )
    return tables


def parse(target: Path) -> Path:
    """Run `dbt parse` (no data needed) and return the manifest it writes."""
    subprocess.run(
        [
            "dbt", "parse", "--quiet",
            "--project-dir", str(TRANSFORM_DIR),
            "--profiles-dir", str(TRANSFORM_DIR),
            "--target-path", str(target),
            "--log-path", str(target / "logs"),
            # Sources need a snapshot path to render, though parsing never reads it.
            "--vars", json.dumps({"usaspending_snapshot": "unused"}),
        ],
        check=True,
    )  # fmt: skip
    return target / "manifest.json"


def render(tables: Tables, level: int = 2) -> str:
    """Markdown: one section per table, headed at `level`, with a column table."""
    sections = []
    for name, table in tables.items():
        rows = "\n".join(
            f"| `{column}` | {c['type']} | {c['description'].replace('|', '\\|')} |"
            for column, c in table["columns"].items()
        )
        sections.append(
            f"{'#' * level} {name}\n\n{table['description']}\n\n"
            f"| Column | Type | Description |\n|---|---|---|\n{rows}\n"
        )
    return "\n".join(sections)


def document(tables: Tables) -> str:
    return f"""# Data dictionary

<!-- Generated by `make data-docs` from data/transform/models/**/_*.yml. Don't edit by hand. -->

The tables in every [data release](README.md). Column names and types are a contract: a release
never removes or retypes a column without saying so in its notes. The same descriptions are
attached to the tables when you `attach` the catalog in DuckDB (see `duckdb_columns()`).

{render(tables)}"""


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if DICTIONARY.md is stale")
    args = parser.parse_args(argv)
    with tempfile.TemporaryDirectory() as tmp:
        text = document(published_tables(parse(Path(tmp) / "target")))
    if not args.check:
        DICTIONARY.write_text(text)
        print(f"Wrote {DICTIONARY.relative_to(graph.ROOT)}")
    elif DICTIONARY.read_text() != text:
        sys.exit(f"error: {DICTIONARY.relative_to(graph.ROOT)} is stale; run `make data-docs`")


if __name__ == "__main__":
    main()
